#!/bin/sh
# -----------------------------------------------------------------------------
# Entrypoint for the Terminal WebUI container.
#
# - Generates ~/.bitcoin/bitcoin.conf from BITCOIND_* env vars so `bitcoin-cli`
#   in the sandbox reads the same credentials the Python backend uses.
# - Two RPC auth modes: `password` (default) and `cookie`. In cookie mode the
#   bitcoind data volume must be mounted read-only at /bitcoind-data so that
#   bitcoin-cli can read .cookie via -rpccookiefile=...
# - Targets the project's Signet node (rpcport 38332), reusing the bitcoind
#   container exposed by the main compose stack.
# - Starts uvicorn with proxy-headers enabled so logs show real client IPs.
# -----------------------------------------------------------------------------

set -eu

BITCOIN_DIR="${HOME:-/home/sandbox}/.bitcoin"
BITCOIND_HOST="${BITCOIND_HOST:-bitcoind}"
BITCOIND_PORT="${BITCOIND_PORT:-38332}"
BITCOIND_AUTH_MODE="${BITCOIN_RPC_AUTH_MODE:-password}"
BITCOIND_COOKIE_FILE="${BITCOIN_RPC_COOKIE_FILE:-/bitcoind-data/signet/.cookie}"

mkdir -p "$BITCOIN_DIR"

if [ "$BITCOIND_AUTH_MODE" = "cookie" ]; then
    cat > "$BITCOIN_DIR/bitcoin.conf" <<EOF
# Auto-generated by entrypoint.sh — cookie-auth mode.
signet=1

[signet]
rpcconnect=${BITCOIND_HOST}
rpcport=${BITCOIND_PORT}
rpccookiefile=${BITCOIND_COOKIE_FILE}
EOF
else
    cat > "$BITCOIN_DIR/bitcoin.conf" <<EOF
# Auto-generated by entrypoint.sh — password-auth mode.
signet=1

[signet]
rpcconnect=${BITCOIND_HOST}
rpcport=${BITCOIND_PORT}
rpcuser=${BITCOIND_USER:-bitcoin}
rpcpassword=${BITCOIND_PASS:-bitcoin}
EOF
fi

chmod 600 "$BITCOIN_DIR/bitcoin.conf"

exec uvicorn app:app \
    --host 0.0.0.0 \
    --port 8181 \
    --app-dir /app \
    --proxy-headers \
    --forwarded-allow-ips='*'
